import { motion, useInView } from "framer-motion";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import { ParallaxBackground } from "@/components/ParallaxBackground";
import { AnimatedHeading, AnimatedText } from "@/components/AnimatedHeading";
import { PhoneCarousel } from "@/components/PhoneCarousel";
import { useRef } from "react";
import { portfolioItems } from "@/data/portfolioItems";

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.1,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 50, scale: 0.95 },
  visible: {
    opacity: 1,
    y: 0,
    scale: 1,
    transition: { 
      duration: 0.6, 
      ease: "easeOut" as const,
    },
  },
};

// Handpicked homepage preview items. Each needs:
//   1. A demoUrl (for the 'Tap to try it live' iframe)
//   2. A server-side phone screenshot at /phone-shots/<slug>.jpg
//      (generated by /opt/prerender/phone-screenshots.mjs on server 38)
//
// Some entries are REAL delivered client work (visible on /portfolio) and
// some are SAMPLE designs (visible only on /designs). We badge each so the
// audience isn't misled by mixing them under a single "real work" header.
// A slug is a real portfolio client if the underlying portfolioItems entry
// has a demoLabel set (that's the same rule /portfolio + /designs use).
const previewItems = [
  portfolioItems.find(p => p.slug === "baby-boy-coleman-christening"),
  portfolioItems.find(p => p.slug === "pastor-mensah-retirement"),
  portfolioItems.find(p => p.slug === "sarah-john-wedding"),
  portfolioItems.find(p => p.slug === "baby-adjoa-naming"),
  portfolioItems.find(p => p.slug === "dr-mensah-graduation"),
  portfolioItems.find(p => p.slug === "mama-akosua-memorial"),
  portfolioItems.find(p => p.slug === "baby-kwame-naming"),
  portfolioItems.find(p => p.slug === "novastream-conference"),
  portfolioItems.find(p => p.slug === "frank-hannah-engagement"),
].filter(Boolean) as typeof portfolioItems;

export function PortfolioPreviewSection() {
  const headerRef = useRef<HTMLDivElement>(null);
  const gridRef = useRef<HTMLDivElement>(null);
  const isHeaderInView = useInView(headerRef, { once: true, amount: 0.3 });
  const isGridInView = useInView(gridRef, { once: true, amount: 0.15 });

  return (
    <section className="py-20 lg:py-28 bg-background relative overflow-hidden">
      <ParallaxBackground variant="gradient" />
      <div className="container mx-auto px-4 lg:px-8 relative">
        {/* Header */}
        <motion.div 
          ref={headerRef}
          className="text-center mb-12"
          initial={{ opacity: 0, y: 50 }}
          animate={isHeaderInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 50 }}
          transition={{ duration: 0.7, ease: [0.25, 0.46, 0.45, 0.94] }}
        >
          <AnimatedHeading
            as="span"
            variant="fade-up"
            className="inline-block px-4 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4"
          >
            Sample Designs &amp; Real Events
          </AnimatedHeading>
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-foreground mb-4">
            <AnimatedText text="See It" className="justify-center" />
            {" "}
            <AnimatedHeading
              as="span"
              variant="blur"
              delay={0.2}
              className="text-primary inline-block"
            >
              in Action
            </AnimatedHeading>
          </h2>
          <AnimatedHeading
            as="p"
            variant="fade-up"
            delay={0.3}
            className="text-muted-foreground text-lg max-w-2xl mx-auto"
          >
            Live invitations across the categories we build for — a mix of real client work and template designs you can order for your own event.
          </AnimatedHeading>
        </motion.div>

        {/* Phone-mockup carousel — real screenshots of each live invitation,
            with 'Tap to try it live' iframe upgrade on the front phone */}
        <motion.div
          ref={gridRef}
          variants={containerVariants}
          initial="hidden"
          animate={isGridInView ? "visible" : "hidden"}
        >
          <PhoneCarousel items={previewItems} />
        </motion.div>

        {/* View All Button */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="text-center mt-12"
        >
          <Button asChild variant="default" size="lg">
            <Link to="/portfolio">
              View All Portfolio
              <ArrowRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
        </motion.div>
      </div>
    </section>
  );
}
