import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/service-anniversary.jpg";

export default function AnniversaryInvitations() {
  return <EventPageTemplate config={{
    seoTitle: "Anniversary & Vow Renewal Invitations Ghana — Digital & Interactive",
    seoDesc: "Beautiful digital anniversary and vow renewal invitations for Ghanaian couples. Silver, gold and pearl milestone designs — RSVP tracking, memory wall, family gallery and livestream — one link every relative can open.",
    seoKeywords: "anniversary invitation Ghana, vow renewal invitation, 25th anniversary invite, 50th anniversary Ghana, digital anniversary invitation Accra",
    canonical: "/anniversary-invitations",
    eventLabel: "🥂 Anniversary & Vow Renewal",
    heroHeading: "Years of love.",
    heroHeadingHighlight: "One elegant invite.",
    heroSubheading: "Silver, gold, pearl — the milestone deserves more than a JPEG.",
    heroDescription: "VibeLink builds an interactive anniversary invitation that honours the years — a milestone-tailored design, family and church acknowledgement, memory wall, gallery of the journey, RSVP and livestream, shared as one beautiful link every relative can open.",
    heroImage: heroImg,
    heroImageAlt: "Ghanaian couple celebrating an anniversary",
    blob1Color: "linear-gradient(135deg,#D4AF37,#fbbf24)",
    blob2Color: "linear-gradient(135deg,#B76E79,#f472b6)",
    blob3Color: "linear-gradient(135deg,#7c2d12,#c2410c)",
    badgeBg: "rgba(212,175,55,0.10)",
    badgeText: "#8B7355",
    badgeBorder: "rgba(212,175,55,0.3)",
    highlightGradient: "linear-gradient(135deg,#D4AF37,#B76E79,#7c2d12)",
    pillBg: "rgba(212,175,55,0.08)",
    pillBorder: "rgba(212,175,55,0.25)",
    pillText: "#8B7355",
    cardTopGradient: "linear-gradient(90deg,#D4AF37,#B76E79,#7c2d12)",
    ctaBtnClass: "anniversary",
    ctaBtnShadow: "0 10px 30px rgba(212,175,55,0.35)",
    getStartedEventType: "Anniversary",
    features: [
      { icon: "🥂", title: "Milestone-Tailored Design", desc: "Silver for 25, pearl for 30, ruby for 40, gold for 50 — the design honours the year." },
      { icon: "💐", title: "Memory Wall", desc: "Family and friends leave their favourite memory of you as a couple — kept forever." },
      { icon: "📸", title: "Journey Gallery", desc: "Photos from your wedding, first home, children, right up to today — the story on one page." },
      { icon: "📅", title: "Save the Date", desc: "One tap and the celebration is on every guest's calendar." },
      { icon: "📍", title: "Venue Map", desc: "Church, garden, hall — guests tap and Google Maps opens directly." },
      { icon: "💌", title: "RSVP Tracking", desc: "Know exactly how many attending, how many meals to prepare." },
      { icon: "⛪", title: "Vow Renewal Programme", desc: "Full order of service if you're renewing your vows in church." },
      { icon: "👗", title: "Dress Code Display", desc: "Colour of the day, cloth pattern, style — everyone dresses to the theme." },
      { icon: "🎵", title: "Your Song", desc: "Embed the song from your wedding day — plays softly when guests open the invite." },
      { icon: "📺", title: "Livestream", desc: "Children abroad, siblings in diaspora — everyone joins the celebration live." },
      { icon: "🌍", title: "Diaspora Ready", desc: "Family in the UK, US, Germany, Canada — all celebrating with you on one link." },
      { icon: "🔗", title: "One Beautiful Link", desc: "Share on WhatsApp, in the family group — works on every phone, every device." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "For most anniversaries, Classic Vibe covers what matters — milestone design, memory wall, journey gallery, RSVP and 2 revisions. For a full 25th, 40th or 50th with livestream and Prestige styling, Prestige Vibe is ideal.",
    testimonials: [
      { name: "Mr. & Mrs. Otchere", location: "Accra", quote: "Our 25th silver anniversary invite went to family we hadn't seen in years. The memory wall filled up with stories our children had never heard. We printed the whole wall as a keepsake." },
      { name: "Nana & Auntie Adjoa", location: "Kumasi", quote: "For our 40th, VibeLink built us a ruby-themed page with our wedding photo next to our grandchildren. My children in Canada and London joined by livestream. It was the best gift." },
      { name: "Rev. & Mrs. Owusu", location: "Tema", quote: "We renewed our vows for our 30th. The digital invitation carried the whole programme, the church order of service, and our journey in photos. Elegant. Dignified. Perfect for a pastor's family." },
    ],
    faqs: [
      { q: "Do you tailor the design to the milestone year?", a: "Yes — silver palette for 25, pearl for 30, ruby for 40, gold for 50. Or tell us the theme you want and we design to match. The year is the star of the invitation." },
      { q: "Can we include a vow renewal church programme?", a: "Absolutely. If you're renewing your vows in church, we build in the full order of service — processional, readings, exchange of vows, closing prayers — so guests follow along on their phones." },
      { q: "Can we show photos across the years?", a: "Yes. The journey gallery is designed for exactly this — wedding photo, first home, children growing, right up to today. Guests scroll through decades of your story." },
      { q: "Is the memory wall private?", a: "You choose — public (every guest sees every memory) or private (only you and your spouse see them, as a keepsake). Most couples pick public, then print the memories after the day." },
      { q: "How do we handle diaspora family?", a: "Livestream is embedded in the invitation — children and siblings in the UK, US, Canada or Germany open the same link, watch live, leave a memory. No app, no login." },
      { q: "How soon can the invitation be ready?", a: "Standard delivery is 5–7 days. Anniversary celebrations planned last-minute can be rushed in 48 hours for a small fee." },
    ],
    ctaHeadline: "Honour the years the way they deserve.",
  }} />;
}
