import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-birthday.jpg";

export default function BirthdayInvitations() {
  return <EventPageTemplate config={{
    seoTitle: "Birthday & Anniversary Invitations Ghana — Digital & Fun",
    seoDesc: "Make your birthday or anniversary unforgettable with a live, interactive digital invitation. RSVP, countdown, gallery and wish wall — all in one shareable link.",
    seoKeywords: "digital birthday invitation Ghana, birthday invite WhatsApp, anniversary invitation Ghana, birthday party invite link",
    canonical: "/birthday",
    eventLabel: "🎂 Birthdays & Anniversaries",
    heroHeading: "Make Your",
    heroHeadingHighlight: "Celebration Unforgettable.",
    heroSubheading: "More than a WhatsApp flyer.",
    heroDescription: "A live, interactive birthday or anniversary invitation with countdown, RSVP, gallery and a wish wall. Your guests will remember it long after the party — and so will you.",
    heroImage: heroImg,
    heroImageAlt: "Birthday celebration in Ghana",
    blob1Color: "linear-gradient(135deg,#f97316,#ea580c)",
    blob2Color: "linear-gradient(135deg,#D4AF37,#fbbf24)",
    blob3Color: "linear-gradient(135deg,#fb923c,#f97316)",
    badgeBg: "rgba(234,88,12,0.08)",
    badgeText: "#c2410c",
    badgeBorder: "rgba(234,88,12,0.2)",
    highlightGradient: "linear-gradient(135deg,#ea580c,#D4AF37,#f97316)",
    pillBg: "rgba(234,88,12,0.07)",
    pillBorder: "rgba(234,88,12,0.2)",
    pillText: "#c2410c",
    cardTopGradient: "linear-gradient(90deg,#ea580c,#D4AF37,#fb923c)",
    ctaBtnClass: "birthday",
    ctaBtnShadow: "0 10px 30px rgba(234,88,12,0.3)",
    getStartedEventType: "Birthday",
    features: [
      { icon: "💌", title: "RSVP Tracking", desc: "Know exactly who's coming before the party." },
      { icon: "⏳", title: "Live Countdown", desc: "Build hype with a countdown to the big day." },
      { icon: "📍", title: "Venue Map", desc: "Guests navigate directly — no one gets lost." },
      { icon: "📸", title: "Photo Gallery", desc: "Share memories from past birthdays and the celebration." },
      { icon: "💝", title: "Wish Wall", desc: "Guests leave birthday messages and well-wishes online." },
      { icon: "🎵", title: "Background Music", desc: "Set the party mood with your favourite track." },
      { icon: "📱", title: "MoMo Contributions", desc: "Friends and family send gifts via Mobile Money." },
      { icon: "📺", title: "Livestream", desc: "Friends abroad join the celebration live." },
      { icon: "🔗", title: "One Link", desc: "Share on WhatsApp — works on every device." },
      { icon: "🎈", title: "Animated Design", desc: "Fun, vibrant design that sets the party tone." },
      { icon: "🎉", title: "Surprise Mode", desc: "Hide details for a surprise party — reveal at the right time." },
      { icon: "✨", title: "Custom Style", desc: "Your colours, your theme, your personality." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "Classic is perfect for birthdays and anniversaries — RSVP, gallery, wish wall and venue map. For milestone celebrations (50th, 60th, Silver Anniversary), Prestige gives you everything.",
    testimonials: [
      { name: "Pastor Emmanuel Acheampong", location: "Accra", quote: "We used VibeLink for our church anniversary. 400+ attendees, all got the link via WhatsApp. The wish wall was full before the day!" },
      { name: "Akosua Frimpong", location: "Kumasi", quote: "My mum's 60th birthday invitation was so beautiful she printed it out and framed it. We still got everyone's RSVP through the digital link!" },
      { name: "Kofi Asante", location: "London, UK", quote: "My wife's surprise 40th was a hit partly because of the invitation. People were hyped before they even arrived." },
    ],
    faqs: [
      { q: "Can I do a surprise party with this?", a: "Yes — we can hide venue details until a set time or add a password so only confirmed guests see the full details." },
      { q: "Can friends contribute monetary gifts?", a: "Yes. MoMo contribution integration lets guests send cash gifts directly, tracked in real time." },
      { q: "Can I use it for an anniversary too?", a: "Absolutely — Silver, Golden or any anniversary. The invitation is fully customised for your milestone." },
      { q: "How quickly can it be ready?", a: "5–7 days standard, 48 hours rush delivery." },
    ],
    ctaHeadline: "Your celebration deserves better than a flyer.",
  }} />;
}
