import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-church.jpg";

export default function ChurchEvents() {
  return <EventPageTemplate config={{
    seoTitle: "Church Event Invitations Ghana — Digital & Interactive",
    seoDesc: "Digital invitations for church services, crusades, conventions and special events in Ghana. RSVP, programme, livestream and more — all in one shareable link.",
    seoKeywords: "church event invitation Ghana, crusade invitation digital, church programme Ghana, church service invite WhatsApp",
    canonical: "/church-events",
    eventLabel: "⛪ Church Events",
    heroHeading: "Invite Your",
    heroHeadingHighlight: "Congregation with Grace.",
    heroSubheading: "Interactive, not just a bulletin.",
    heroDescription: "Digital invitations for church services, conventions, crusades and special events — with full programme, RSVP, livestream for members abroad, and a prayer wall. Everything in one powerful link.",
    heroImage: heroImg,
    heroImageAlt: "Church event in Ghana",
    blob1Color: "linear-gradient(135deg,#7c3aed,#5b21b6)",
    blob2Color: "linear-gradient(135deg,#D4AF37,#c0a030)",
    blob3Color: "linear-gradient(135deg,#a78bfa,#8b5cf6)",
    badgeBg: "rgba(91,33,182,0.08)",
    badgeText: "#5b21b6",
    badgeBorder: "rgba(91,33,182,0.2)",
    highlightGradient: "linear-gradient(135deg,#5b21b6,#D4AF37,#7c3aed)",
    pillBg: "rgba(91,33,182,0.07)",
    pillBorder: "rgba(91,33,182,0.2)",
    pillText: "#5b21b6",
    cardTopGradient: "linear-gradient(90deg,#5b21b6,#D4AF37,#a78bfa)",
    ctaBtnClass: "church",
    ctaBtnShadow: "0 10px 30px rgba(91,33,182,0.3)",
    getStartedEventType: "Church Event",
    features: [
      { icon: "💌", title: "RSVP & Registration", desc: "Track attendance and manage capacity for your event." },
      { icon: "⏳", title: "Countdown Timer", desc: "Build anticipation for special services and conventions." },
      { icon: "📋", title: "Full Programme", desc: "Order of service, sermon schedule, hymn numbers — all included." },
      { icon: "📍", title: "Church Location Map", desc: "New visitors navigate directly — no confusion." },
      { icon: "📺", title: "Livestream", desc: "Members abroad and shut-ins watch live from the link." },
      { icon: "💝", title: "Prayer Wall", desc: "Members submit prayer requests and testimonies online." },
      { icon: "📸", title: "Photo Gallery", desc: "Share event photos and memories from past services." },
      { icon: "🎵", title: "Worship Music", desc: "Set a worshipful atmosphere with background music." },
      { icon: "📱", title: "Offering Link", desc: "Members give via Mobile Money — secure and tracked." },
      { icon: "🔗", title: "One Link", desc: "Share on WhatsApp to the entire congregation instantly." },
      { icon: "🌍", title: "Diaspora Ready", desc: "Church members abroad stay connected to every event." },
      { icon: "✨", title: "Custom Branding", desc: "Your church logo, colours and theme — professional every time." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "Classic is ideal for most church events — RSVP, full programme, livestream embed, maps and 90 days hosting. For large conventions and crusades with high attendance, Prestige or Royal is recommended.",
    testimonials: [
      { name: "Pastor Emmanuel Acheampong", location: "Accra", quote: "We used it for our annual convention. 400+ attendees, all got the link via WhatsApp. The prayer wall was full by the morning of the event. Worth every pesewa." },
      { name: "Deaconess Akua Boateng", location: "Kumasi", quote: "Our Sunday special service invitation looked so professional. New visitors told us they felt welcome even before they arrived because of the invitation." },
      { name: "Elder Kofi Mensah", location: "London, UK", quote: "Our church in Ghana started using VibeLink for events. Members in the diaspora are more connected than ever — we watch every service live." },
    ],
    faqs: [
      { q: "Can I use this for a weekly church service?", a: "Yes — though it works best for special events, conventions, crusades, anniversaries and dedication services where you want to track attendance." },
      { q: "Can members give offerings through the invitation?", a: "Yes. MoMo offering integration lets members give directly via Mobile Money, tracked in real time for the church treasurer." },
      { q: "Can I add a full order of service?", a: "Absolutely. We include the complete order of service — welcome, scripture readings, worship set, sermon, altar call, benediction — whatever your programme needs." },
      { q: "Can members abroad watch live?", a: "Yes. Livestream is embedded directly in the invitation — members anywhere in the world can watch without any separate link or app." },
    ],
    ctaHeadline: "Connect your congregation — wherever they are.",
  }} />;
}
