import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-corporate.jpg";

export default function CorporateEvents() {
  return <EventPageTemplate config={{
    seoTitle: "Corporate Event Invitations Ghana — Professional & Digital",
    seoDesc: "Professional digital invitations for corporate events, conferences, product launches and AGMs in Ghana. RSVP tracking, programme and branding — all in one link.",
    seoKeywords: "corporate event invitation Ghana, conference invitation digital, product launch invite Ghana, AGM invitation professional",
    canonical: "/corporate-events",
    eventLabel: "💼 Corporate Events",
    heroHeading: "Elevate Your",
    heroHeadingHighlight: "Brand Events.",
    heroSubheading: "Professional, not plain.",
    heroDescription: "Premium digital invitations for conferences, product launches, AGMs and corporate gatherings — with RSVP management, full event programme, maps and your company branding. First impressions matter.",
    heroImage: heroImg,
    heroImageAlt: "Corporate event in Ghana",
    blob1Color: "linear-gradient(135deg,#0f172a,#1e293b)",
    blob2Color: "linear-gradient(135deg,#D4AF37,#c0a030)",
    blob3Color: "linear-gradient(135deg,#334155,#475569)",
    badgeBg: "rgba(15,23,42,0.08)",
    badgeText: "#0f172a",
    badgeBorder: "rgba(15,23,42,0.2)",
    highlightGradient: "linear-gradient(135deg,#0f172a,#D4AF37,#334155)",
    pillBg: "rgba(15,23,42,0.07)",
    pillBorder: "rgba(15,23,42,0.15)",
    pillText: "#1e293b",
    cardTopGradient: "linear-gradient(90deg,#0f172a,#D4AF37,#475569)",
    ctaBtnClass: "corporate",
    ctaBtnShadow: "0 10px 30px rgba(15,23,42,0.3)",
    getStartedEventType: "Corporate Event",
    features: [
      { icon: "💌", title: "RSVP & Registration", desc: "Manage attendance and capacity for your corporate event." },
      { icon: "⏳", title: "Countdown Timer", desc: "Build anticipation for launches and conferences." },
      { icon: "📋", title: "Event Programme", desc: "Full agenda, speaker bios and session schedule." },
      { icon: "📍", title: "Venue Maps", desc: "Delegates navigate directly — parking, entrance and all." },
      { icon: "📺", title: "Livestream", desc: "Remote attendees and executives join live from the link." },
      { icon: "📸", title: "Media Gallery", desc: "Share event photos and marketing materials." },
      { icon: "🎵", title: "Brand Audio", desc: "Set a professional tone with subtle background audio." },
      { icon: "🔗", title: "One Link", desc: "Share with delegates via email or WhatsApp instantly." },
      { icon: "🌍", title: "International Ready", desc: "Overseas stakeholders and delegates access it anywhere." },
      { icon: "🏢", title: "Company Branding", desc: "Your logo, brand colours and professional identity throughout." },
      { icon: "📊", title: "Attendance Tracking", desc: "Real-time RSVP data for event planning and catering." },
      { icon: "✨", title: "White-label Option", desc: "Remove VibeLink branding for fully branded corporate events." },
    ],
    recommendedPackage: "Prestige or Royal Vibe",
    recommendedDesc: "For corporate events, Prestige (GHS 2,500) covers most needs — RSVP, programme, gallery and livestream. For high-profile events requiring custom domain and white-label branding, Royal Vibe is recommended.",
    testimonials: [
      { name: "Emmanuel Kweku Darko", location: "Accra Business District", quote: "We used VibeLink for our product launch. The invitation looked more professional than anything we'd used before. Delegates were impressed from the first click." },
      { name: "Corporate Events Team", location: "Kumasi", quote: "Managing RSVPs for 200+ delegates used to be a nightmare. VibeLink's live tracking made catering and seating planning effortless." },
      { name: "Sandra Asante", location: "London, UK", quote: "Our AGM had shareholders in Ghana and abroad. Having the livestream embedded in the invitation meant everyone could join without a separate Zoom link." },
    ],
    faqs: [
      { q: "Can I have our company branding on the invitation?", a: "Yes — we include your company logo, brand colours and design identity throughout. Royal Vibe also offers full white-label with no VibeLink branding." },
      { q: "Can I manage multiple sessions or speakers?", a: "Yes. We include a full event programme with session times, speaker names and descriptions. Ideal for conferences and multi-session events." },
      { q: "Can remote delegates join via livestream?", a: "Yes. We embed your livestream link so remote stakeholders and overseas delegates can join directly from the invitation." },
      { q: "Is the RSVP data exportable for planning?", a: "Yes. All RSVP responses are accessible in your admin dashboard and can be used for seating, catering and capacity planning." },
    ],
    ctaHeadline: "Make your next corporate event unforgettable.",
  }} />;
}
