import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-engagement.jpg";

export default function EngagementInvitations() {
  return <EventPageTemplate config={{
    seoTitle: "Engagement Invitations Ghana — Customary Marriage & Knocking",
    seoDesc: "Beautiful digital engagement invitations for Ghanaian customary marriages and knocking ceremonies. Kente-inspired designs, respectful family acknowledgement, dress code, RSVP tracking — one link, every relative.",
    seoKeywords: "engagement invitations Ghana, customary marriage invitation, knocking ceremony invite, traditional wedding invitation Ghana, digital engagement invitation Accra",
    canonical: "/engagement-invitations",
    eventLabel: "💍 Engagement Invitations",
    heroHeading: "Two families.",
    heroHeadingHighlight: "One dignified invite.",
    heroSubheading: "For the knocking, the customary, the engagement.",
    heroDescription: "VibeLink builds an interactive engagement invitation that honours the customary side of your union — kente-inspired design, respectful family acknowledgement, dress code display, wish wall and RSVP tracking, shared in one link every uncle and aunty can open.",
    heroImage: heroImg,
    heroImageAlt: "Ghanaian traditional engagement ceremony",
    blob1Color: "linear-gradient(135deg,#D4AF37,#fbbf24)",
    blob2Color: "linear-gradient(135deg,#B76E79,#f472b6)",
    blob3Color: "linear-gradient(135deg,#9333ea,#7c3aed)",
    badgeBg: "rgba(212,175,55,0.10)",
    badgeText: "#8B7355",
    badgeBorder: "rgba(212,175,55,0.3)",
    highlightGradient: "linear-gradient(135deg,#D4AF37,#B76E79,#9333ea)",
    pillBg: "rgba(212,175,55,0.08)",
    pillBorder: "rgba(212,175,55,0.25)",
    pillText: "#8B7355",
    cardTopGradient: "linear-gradient(90deg,#D4AF37,#B76E79,#9333ea)",
    ctaBtnClass: "engagement",
    ctaBtnShadow: "0 10px 30px rgba(212,175,55,0.35)",
    getStartedEventType: "Engagement",
    features: [
      { icon: "🌟", title: "Adinkra Symbol Design", desc: "Osrane ne Nsoromma, Sankofa, Gye Nyame — the symbol that carries your story." },
      { icon: "🧵", title: "Kente-inspired Palette", desc: "Traditional colour combinations chosen to honour the two families." },
      { icon: "🤝", title: "Family Acknowledgement", desc: "Both sides honoured respectfully — as much or as little detail as your elders prefer." },
      { icon: "📅", title: "Save the Date", desc: "One tap adds the ceremony to every guest's calendar." },
      { icon: "📍", title: "Venue Map", desc: "House address or hall — guests tap and Google Maps opens directly." },
      { icon: "💌", title: "RSVP Tracking", desc: "Know exactly how many relatives, how many meals, before the day." },
      { icon: "💐", title: "Wish Wall", desc: "Every guest leaves a blessing for the couple — kept as a digital keepsake, forever." },
      { icon: "👗", title: "Dress Code Display", desc: "Colour of the day, cloth pattern, style — everyone dresses to the theme." },
      { icon: "📸", title: "Pre-engagement Gallery", desc: "Photos of the couple and both families — introduces guests to the story." },
      { icon: "📋", title: "Ceremony Programme", desc: "Order of proceedings, from knocking to closing prayers." },
      { icon: "📺", title: "Livestream Ready", desc: "Diaspora relatives watch the ceremony live — no app, no login." },
      { icon: "🔗", title: "One Beautiful Link", desc: "Share on WhatsApp, on the family group — works on every phone." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "For most Ghanaian engagements, Classic Vibe covers what matters — Adinkra design, respectful family acknowledgement, RSVP tracking, dress-code display, wish wall and 2 revisions. For larger customary ceremonies with livestream and Prestige styling, upgrade to Prestige Vibe.",
    testimonials: [
      { name: "Akosua & Yaw", location: "Kumasi", quote: "Our elders were sceptical of a digital invitation for the knocking. When they saw the Adinkra design and how respectfully our two families were introduced, they were the ones sharing it." },
      { name: "Ama Boateng", location: "Accra", quote: "The wish wall filled up with blessings from aunties in London and Frankfurt within a day. The whole family felt part of the ceremony even before it started." },
      { name: "Kwame Mensah", location: "Berlin", quote: "I'm in Germany, my fiancée is in Ghana. The livestream let my whole family here watch the customary — like being in the room." },
    ],
    faqs: [
      { q: "Can you design in a specific Adinkra symbol?", a: "Yes. Tell us the symbol — Osrane ne Nsoromma, Sankofa, Gye Nyame, Nkyinkyim — and we integrate it into the invitation as the central motif." },
      { q: "Can we mention both families on the invitation?", a: "Yes — respectfully, and as much or as little as your elders decide. Some families prefer just the two heads of family named; others want a fuller acknowledgement. We follow your guidance." },
      { q: "Do you handle any money on the invitation?", a: "No. Traditional dowry / bride price is a private matter between the two families — we deliberately keep money off the invitation. What we do include is a wish wall so guests can leave blessings publicly." },
      { q: "How do we handle two ceremonies (engagement + wedding)?", a: "Most couples order two separate invitations — one for the customary/engagement, one for the white wedding. Different designs, different guest lists, different links. We offer a bundle discount." },
      { q: "Can we display the dress code and cloth pattern?", a: "Absolutely. Colour of the day, kente pattern, style guidance — displayed clearly so every guest arrives in the right cloth." },
      { q: "Is livestream included?", a: "Livestream embedding is included from Prestige Vibe upwards. For Classic Vibe, we can add it as a small upgrade. Family abroad watches on any device." },
    ],
    ctaHeadline: "Honour the two families with a proper digital invitation.",
  }} />;
}
