import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-funeral.jpg";

export default function FuneralPrograms() {
  return <EventPageTemplate config={{
    seoTitle: "Funeral Programs Ghana — Digital Memorial Pages",
    seoDesc: "Dignified digital funeral programs and memorial pages for Ghanaian families. Share tribute messages, livestream, order of service and gallery — all in one respectful link.",
    seoKeywords: "digital funeral programs Ghana, memorial page Ghana, funeral invitation Accra, online tribute page",
    canonical: "/funeral-programs",
    eventLabel: "🕊️ Funeral Programs & Memorials",
    heroHeading: "Honor Their",
    heroHeadingHighlight: "Legacy with Dignity.",
    heroSubheading: "More than a printed programme.",
    heroDescription: "A living memorial page your family can visit from anywhere in the world — tribute messages, gallery, order of service and livestream, all in one dignified link shared instantly via WhatsApp.",
    heroImage: heroImg,
    heroImageAlt: "Dignified memorial ceremony",
    blob1Color: "linear-gradient(135deg,#475569,#1e3a5f)",
    blob2Color: "linear-gradient(135deg,#D4AF37,#c0a030)",
    blob3Color: "linear-gradient(135deg,#94a3b8,#64748b)",
    badgeBg: "rgba(30,58,95,0.08)",
    badgeText: "#1e3a5f",
    badgeBorder: "rgba(30,58,95,0.2)",
    highlightGradient: "linear-gradient(135deg,#1e3a5f,#D4AF37,#475569)",
    pillBg: "rgba(30,58,95,0.07)",
    pillBorder: "rgba(30,58,95,0.2)",
    pillText: "#1e3a5f",
    cardTopGradient: "linear-gradient(90deg,#1e3a5f,#D4AF37,#475569)",
    ctaBtnClass: "funeral",
    ctaBtnShadow: "0 10px 30px rgba(30,58,95,0.3)",
    getStartedEventType: "Funeral",
    features: [
      { icon: "📋", title: "Order of Service", desc: "Full funeral programme — processional, tributes, hymns, committal." },
      { icon: "💬", title: "Tribute Wall", desc: "Family and friends leave heartfelt tributes and condolences online." },
      { icon: "📸", title: "Photo Gallery", desc: "A collection of cherished memories of their life." },
      { icon: "📺", title: "Livestream", desc: "Family abroad watch the service live — no app needed." },
      { icon: "📍", title: "Venue Maps", desc: "Church, burial site and reception — guests navigate easily." },
      { icon: "⏳", title: "Countdown", desc: "Gentle countdown to the funeral date." },
      { icon: "🔗", title: "Share Instantly", desc: "One WhatsApp link reaches family across Ghana and the diaspora." },
      { icon: "📖", title: "Obituary Section", desc: "Full life story and biography — included free on request." },
      { icon: "🕯️", title: "Memorial Page", desc: "The page stays live after the funeral — a permanent tribute." },
      { icon: "🌍", title: "Diaspora Ready", desc: "Works perfectly on every device, everywhere in the world." },
      { icon: "💐", title: "Flower Tributes", desc: "Guests can send virtual flower tributes with messages." },
      { icon: "📱", title: "MoMo Donations", desc: "Family contributions collected directly via Mobile Money." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "The Classic package covers everything a dignified funeral programme needs — order of service, tribute wall, gallery, livestream and 90 days hosting. Obituary section is included free.",
    testimonials: [
      { name: "Kwame Asante-Boateng", location: "Kumasi", quote: "We lost my father suddenly and didn't have time for printing. Within two days we had something dignified and beautiful to share with family abroad. It meant everything." },
      { name: "Pastor Emmanuel Acheampong", location: "Accra", quote: "The tribute wall was full of messages from family we hadn't heard from in years. It became a beautiful gathering point for the whole family." },
      { name: "Efua Mensah-Korsah", location: "London, UK", quote: "Being abroad and unable to attend, having the livestream built right into the programme made me feel present. Truly grateful for VibeLink." },
    ],
    faqs: [
      { q: "How quickly can a funeral programme be ready?", a: "We understand time is critical for funerals. Standard delivery is 5–7 days, but rush delivery in 48 hours is available. Contact us on WhatsApp and we'll prioritise your order." },
      { q: "Can the memorial page stay live permanently?", a: "Yes. With extended hosting add-ons, the page can remain accessible for 6 months, 1 year or longer — a permanent digital tribute to their memory." },
      { q: "Can family abroad watch the service live?", a: "Yes. We embed a YouTube or Facebook livestream link directly in the programme so diaspora family can watch in real time from anywhere." },
      { q: "Is the obituary section included?", a: "Yes — the obituary section is included free on request for all funeral programmes. We just need the life story and photos." },
      { q: "Can guests leave tribute messages?", a: "Yes. The tribute wall lets family and friends leave heartfelt messages and condolences directly on the memorial page." },
    ],
    ctaHeadline: "Give their memory the tribute it deserves.",
  }} />;
}
