import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-graduation.jpg";

export default function GraduationInvitations() {
  return <EventPageTemplate config={{
    seoTitle: "Graduation Invitations Ghana — Digital & Interactive",
    seoDesc: "Celebrate your achievement with a stunning digital graduation invitation. RSVP tracking, gallery, countdown and more — all in one shareable link for family and friends.",
    seoKeywords: "digital graduation invitation Ghana, graduation celebration invite, graduation link WhatsApp Ghana, university graduation invitation",
    canonical: "/graduation",
    eventLabel: "🎓 Graduation Celebrations",
    heroHeading: "Celebrate Your",
    heroHeadingHighlight: "Achievement.",
    heroSubheading: "Your hard work deserves more than a flyer.",
    heroDescription: "Share your milestone with a stunning digital graduation invitation. RSVP, countdown, gallery and well-wishing wall — let every guest celebrate your achievement with you in real time.",
    heroImage: heroImg,
    heroImageAlt: "Graduation celebration in Ghana",
    blob1Color: "linear-gradient(135deg,#3b82f6,#1d4ed8)",
    blob2Color: "linear-gradient(135deg,#D4AF37,#fbbf24)",
    blob3Color: "linear-gradient(135deg,#93c5fd,#60a5fa)",
    badgeBg: "rgba(29,78,216,0.08)",
    badgeText: "#1d4ed8",
    badgeBorder: "rgba(29,78,216,0.2)",
    highlightGradient: "linear-gradient(135deg,#1d4ed8,#D4AF37,#3b82f6)",
    pillBg: "rgba(29,78,216,0.07)",
    pillBorder: "rgba(29,78,216,0.2)",
    pillText: "#1d4ed8",
    cardTopGradient: "linear-gradient(90deg,#1d4ed8,#D4AF37,#93c5fd)",
    ctaBtnClass: "graduation",
    ctaBtnShadow: "0 10px 30px rgba(29,78,216,0.3)",
    getStartedEventType: "Graduation",
    features: [
      { icon: "💌", title: "RSVP Tracking", desc: "Know exactly who's joining your celebration." },
      { icon: "⏳", title: "Countdown Timer", desc: "Build excitement with a live countdown to graduation day." },
      { icon: "📍", title: "Venue Map", desc: "Guests navigate to the ceremony and celebration easily." },
      { icon: "📸", title: "Photo Gallery", desc: "Share graduation photos and university memories." },
      { icon: "💝", title: "Congratulations Wall", desc: "Family and friends leave their messages of congratulations." },
      { icon: "🎵", title: "Background Music", desc: "Set a celebratory tone with your favourite song." },
      { icon: "📱", title: "MoMo Contributions", desc: "Family send monetary congratulations via Mobile Money." },
      { icon: "📺", title: "Livestream", desc: "Family abroad watch the ceremony live from the link." },
      { icon: "🔗", title: "One Link", desc: "Share on WhatsApp — works on every device." },
      { icon: "🌍", title: "Diaspora Ready", desc: "Extended family wherever they are feel part of the celebration." },
      { icon: "📅", title: "Save the Date", desc: "Guests add your graduation to their calendars instantly." },
      { icon: "✨", title: "Custom Design", desc: "Your colours, your university, your achievement." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "Classic is perfect for graduations — RSVP tracking, gallery, congratulations wall, venue maps and 90 days hosting. Add a livestream embed for family who can't attend in person.",
    testimonials: [
      { name: "Kofi Mensah", location: "Kumasi", quote: "My graduation invitation was more impressive than some wedding invites I've seen. My lecturers were asking about it!" },
      { name: "Ama Owusu", location: "Accra", quote: "The RSVP feature made planning the after-party so easy. I knew exactly how many people were coming and could plan accordingly." },
      { name: "Emmanuel Darko", location: "London, UK", quote: "I graduated from university in Ghana while my parents were in London. They watched my ceremony live through the invitation. I cried." },
    ],
    faqs: [
      { q: "Can I include both the graduation ceremony and the celebration after?", a: "Yes. We can add multiple event details — ceremony venue, time and reception location — all in one invitation." },
      { q: "Can diaspora family watch the ceremony live?", a: "Yes. We embed a livestream link so your family anywhere in the world can watch in real time." },
      { q: "Can guests contribute monetarily?", a: "Yes — MoMo contribution integration lets family send cash gifts directly via Mobile Money, tracked in real time." },
      { q: "How quickly can it be ready?", a: "Standard delivery is 5–7 days. Rush delivery in 48 hours for urgent ceremonies." },
    ],
    ctaHeadline: "You earned this. Celebrate it properly.",
  }} />;
}
