import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-naming.jpg";

export default function NamingCeremony() {
  return <EventPageTemplate config={{
    seoTitle: "Naming Ceremony Invitations Ghana — Digital & Interactive",
    seoDesc: "Beautiful digital naming ceremony and outdooring invitations for Ghanaian families. RSVP tracking, gallery, countdown and well-wishing wall — all in one shareable link.",
    seoKeywords: "naming ceremony invitation Ghana, outdooring invitation digital, baby dedication Ghana, naming ceremony link WhatsApp",
    canonical: "/naming-ceremony",
    eventLabel: "👶 Naming Ceremony & Outdooring",
    heroHeading: "Welcome Your",
    heroHeadingHighlight: "Little One in Style.",
    heroSubheading: "Not a JPEG — a living celebration.",
    heroDescription: "Share the joy of new life with a digital naming ceremony invitation. RSVP tracking, well-wishing wall, gallery, countdown and venue maps — all in one beautiful link your family will love.",
    heroImage: heroImg,
    heroImageAlt: "Ghanaian naming ceremony celebration",
    blob1Color: "linear-gradient(135deg,#4ade80,#16a34a)",
    blob2Color: "linear-gradient(135deg,#fbbf24,#D4AF37)",
    blob3Color: "linear-gradient(135deg,#86efac,#4ade80)",
    badgeBg: "rgba(22,163,74,0.08)",
    badgeText: "#15803d",
    badgeBorder: "rgba(22,163,74,0.2)",
    highlightGradient: "linear-gradient(135deg,#16a34a,#D4AF37,#4ade80)",
    pillBg: "rgba(22,163,74,0.07)",
    pillBorder: "rgba(22,163,74,0.2)",
    pillText: "#15803d",
    cardTopGradient: "linear-gradient(90deg,#16a34a,#D4AF37,#86efac)",
    ctaBtnClass: "naming",
    ctaBtnShadow: "0 10px 30px rgba(22,163,74,0.3)",
    getStartedEventType: "Naming Ceremony",
    features: [
      { icon: "💌", title: "RSVP Tracking", desc: "Know exactly who's celebrating with you." },
      { icon: "⏳", title: "Live Countdown", desc: "Countdown to the outdooring builds family excitement." },
      { icon: "📍", title: "Venue Map", desc: "Guests navigate directly from the invitation." },
      { icon: "📸", title: "Baby Gallery", desc: "Share first photos — guests love seeing the little one." },
      { icon: "💝", title: "Well-Wishing Wall", desc: "Family leave blessings and congratulations messages." },
      { icon: "🎵", title: "Background Music", desc: "Set a joyful, celebratory mood with music." },
      { icon: "📱", title: "MoMo Contributions", desc: "Family contribute monetary gifts via Mobile Money." },
      { icon: "📋", title: "Order of Ceremony", desc: "Full outdooring programme for all guests." },
      { icon: "📺", title: "Livestream", desc: "Diaspora family watch the naming ceremony live." },
      { icon: "🔗", title: "One Link", desc: "Share via WhatsApp — works on every device." },
      { icon: "🌍", title: "Diaspora Ready", desc: "Family abroad feel part of the celebration." },
      { icon: "✨", title: "Custom Design", desc: "Designed around your baby and your family's style." },
    ],
    recommendedPackage: "Classic Vibe — GHS 1,500",
    recommendedDesc: "Classic covers everything a naming ceremony needs — RSVP, gallery, well-wishing wall, venue maps and 90 days hosting. For large family gatherings with livestream, Prestige is ideal.",
    testimonials: [
      { name: "Sandra & David Nortey", location: "Tema", quote: "The countdown timer got people more excited than anything else. People were sending screenshots in the family group chat for days!" },
      { name: "Abena Asante", location: "Accra", quote: "Our outdooring invitation was so elegant. Everyone was asking who designed it. The well-wishing wall was full of beautiful blessings." },
      { name: "Afia Mensah", location: "London, UK", quote: "My family in Ghana used VibeLink for my niece's naming ceremony. I watched the livestream from London and cried happy tears. So special." },
    ],
    faqs: [
      { q: "What's the difference between a naming ceremony and outdooring invitation?", a: "They're the same thing — we handle both. Whether you call it a naming ceremony, outdooring or baby dedication, we create the perfect invitation for your celebration." },
      { q: "Can guests send monetary gifts through the invitation?", a: "Yes. We can integrate Mobile Money collection directly into the invitation so family and friends can contribute gifts easily." },
      { q: "Can diaspora family watch live?", a: "Yes. We embed a livestream link so family in the UK, US or anywhere can watch the naming ceremony live from the invitation page." },
      { q: "How soon can the invitation be ready?", a: "Standard delivery is 5–7 days. For urgent naming ceremonies, rush delivery in 48 hours is available." },
    ],
    ctaHeadline: "Celebrate new life the way it deserves.",
  }} />;
}
