import { EventPageTemplate } from "@/components/EventPageTemplate";
import heroImg from "@/assets/hero-celebration.jpg";

export default function WeddingInvitations() {
  return <EventPageTemplate config={{
    seoTitle: "Wedding Invitations Ghana — Digital, Live & Interactive",
    seoDesc: "Stop sending JPEGs. VibeLink creates live, interactive wedding invitations with RSVP tracking, countdown timers, photo galleries, wish walls and more. One link. Every guest.",
    seoKeywords: "digital wedding invitations Ghana, wedding invitation link WhatsApp, RSVP wedding Ghana, interactive wedding invite Accra",
    canonical: "/wedding-invitations",
    eventLabel: "💍 Wedding Invitations",
    heroHeading: "Your Wedding.",
    heroHeadingHighlight: "One Perfect Link.",
    heroSubheading: "Stop sending JPEGs and PDFs.",
    heroDescription: "VibeLink creates a live, interactive wedding invitation with RSVP tracking, countdown timers, photo galleries, wish walls and more — shared in one beautiful link, impressive on every screen.",
    heroImage: heroImg,
    heroImageAlt: "Ghanaian wedding celebration",
    blob1Color: "linear-gradient(135deg,#c084fc,#a855f7)",
    blob2Color: "linear-gradient(135deg,#D4AF37,#fbbf24)",
    blob3Color: "linear-gradient(135deg,#f472b6,#ec4899)",
    badgeBg: "rgba(147,51,234,0.08)",
    badgeText: "#7c3aed",
    badgeBorder: "rgba(147,51,234,0.2)",
    highlightGradient: "linear-gradient(135deg,#9333ea,#D4AF37,#ec4899)",
    pillBg: "rgba(147,51,234,0.07)",
    pillBorder: "rgba(147,51,234,0.2)",
    pillText: "#7c3aed",
    cardTopGradient: "linear-gradient(90deg,#9333ea,#D4AF37,#ec4899)",
    ctaBtnClass: "wedding",
    ctaBtnShadow: "0 10px 30px rgba(147,51,234,0.3)",
    getStartedEventType: "Wedding",
    features: [
      { icon: "💌", title: "RSVP Tracking", desc: "Live guest count, meal preferences and attendance dashboard." },
      { icon: "⏳", title: "Live Countdown", desc: "A ticking countdown building excitement for every guest." },
      { icon: "📍", title: "Venue Maps", desc: "Google Maps for church and reception — guests tap and go." },
      { icon: "📸", title: "Photo Gallery", desc: "Pre-wedding and ceremony photos in one beautiful gallery." },
      { icon: "💝", title: "Wish Wall", desc: "Guests leave heartfelt messages — a digital keepsake forever." },
      { icon: "🎵", title: "Background Music", desc: "Your wedding song plays softly when guests open the link." },
      { icon: "📱", title: "MoMo Contributions", desc: "Guests contribute directly via Mobile Money — tracked live." },
      { icon: "📋", title: "Wedding Programme", desc: "Full order of service accessible for every guest." },
      { icon: "📺", title: "Livestream", desc: "Family abroad watch live — no app, no login needed." },
      { icon: "📅", title: "Save the Date", desc: "One-tap to add your date to every guest's calendar." },
      { icon: "🔗", title: "One Link", desc: "Share via WhatsApp. Works perfectly on every device." },
      { icon: "✨", title: "Custom Design", desc: "Your colours, your photos, your style — nothing generic." },
    ],
    recommendedPackage: "Prestige Vibe — GHS 2,500",
    recommendedDesc: "Most couples choose Prestige — it includes photo gallery, RSVP tracking, MoMo donation link, video integration and 5 revisions. For larger weddings with custom domain, Royal Vibe is the one.",
    testimonials: [
      { name: "Abena Owusu", location: "Accra", quote: "When I shared the link people were calling me asking who made it. The RSVP feature alone saved me so many headaches." },
      { name: "Sandra & David Nortey", location: "Tema", quote: "The countdown timer got people more excited than anything else. People were sending screenshots in the family group." },
      { name: "Afia Mensah", location: "London, UK", quote: "Planning from the UK for a Ghana event was stressful. VibeLink made the invitation side effortless." },
    ],
    faqs: [
      { q: "How long does a wedding invitation take?", a: "Standard delivery is 5–7 business days. Rush delivery in 48 hours is available at an additional fee." },
      { q: "Can guests RSVP through the invitation?", a: "Yes. Guests click RSVP, fill a short form, and you see all responses in real time — guest count, meal preferences and messages." },
      { q: "Can both ceremony and reception have separate maps?", a: "Yes. We add Google Maps for every venue — guests tap and navigate directly from the invitation." },
      { q: "Can family abroad access it?", a: "Absolutely. The link works on any device anywhere. You can also embed a livestream so they can watch the ceremony live." },
      { q: "Can I update details after it goes live?", a: "Yes. If venue or time changes, we update it immediately. The link stays the same so you don't need to reshare." },
    ],
    ctaHeadline: "Your guests deserve better than a JPEG.",
  }} />;
}
